# Generated by Django 2.1.7 on 2019-03-17 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate',
            name='slug',
        ),
    ]
