# Generated by Django 2.1.7 on 2019-04-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20190320_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('podcategory', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='form.Cate')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to='form.PodCate'),
        ),
    ]
