# Generated by Django 2.1.7 on 2019-04-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20190415_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcate',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='form.Cate'),
        ),
        migrations.AlterField(
            model_name='podcate',
            name='podcategory',
            field=models.TextField(),
        ),
    ]
