# Generated by Django 2.1.7 on 2019-03-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20190328_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='intent',
            unique_together={('name', 'context')},
        ),
    ]
