# Generated by Django 2.1.7 on 2019-04-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20190415_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('text', models.TextField()),
                ('body_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='body_post', to='form.Post')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccence_cat', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='podcate',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categ', to='form.Cate'),
        ),
        migrations.AddField(
            model_name='essence',
            name='essence_cat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='e_c', to='form.TypeEssence'),
        ),
    ]
